### ISSUE TITLE
datepicker mobile widget screws up Safari (and all other iOS browsers)

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#462] opened 2017-10-06 21:03 UTC
see https://github.com/kobotoolbox/enketo-express/issues/820

looks like the focus and hide events don't work as expected

**Comment by MartijnR** [comment] 2017-10-06 21:56
After a few hours I've come to the conclusion it is not possible to hide default placeholders (dd/mm/yyyy) in date input with pure CSS. Hence we require the mobile-datepicker widget with its ugly JS switching. 

Luckily, the placeholders are not shown on mobile Chrome/Android and All/iOS, so a pragmatic solution is to not instantiate the widget on touchscreens.

**Comment by bsharif** [comment] 2017-12-17 16:06
Martijn,

Is this issue fixed now? 
I notice that on version 1.55.7 (same as https://odk.enke.to/) that date fields on iOS don't seem to load the datepicker, at least not instantly. 
I've found that by locking the iPad screen and unlocking the device then the iOS datepicker does load correctly, on both Chrome and Safari.
I used this XML to test:  https://pastebin.com/u1fhRJ3s
See gif: 
![6cba5f2de0](https://user-images.githubusercontent.com/7132252/34081384-a2f8b6ca-e343-11e7-9ab4-93450131678a.gif)

Thanks

**Comment by bsharif** [comment] 2017-12-17 16:09
DateTime fields however seem to work as intended (by loading the web datepicker and not the iOS datepicker). They do seem to be difficult to interact with in Landscape though as the iOS native keyboard pops up with every tap. A separate issue perhaps.

**Comment by MartijnR** [comment] 2017-12-18 16:46
Thanks! yes, it was fixed, but apparently not any more..

**Comment by MartijnR** [comment] 2017-12-19 22:37
I did fix it initially and then unfixed it with https://github.com/enketo/enketo-core/commit/761a1fb571570230dec198c88e5c6655ce1afa13#diff-a73c4b461ba537eaf757d93402556e48

**Closed** 2017-12-19 23:03 UTC
Labels: bug
