### ISSUE TITLE
Loading enketo form with preset data messes up repeat section

### ISSUE THREAD

**Issue by maina** [enketo/enketo-core#376] opened 2016-07-13 12:27 UTC
To reproduce this issue am using a custom method **loadDraft(xmlDataString)** to load sample data into the form. The sample data loads fine into the form but the repeat section skip logic seems to break after filling in data in the first repeat in that the second repeat looks exactly the same as the first repeat with hidden fields showing.

1. To reproduce the issue go to **https://maina.github.io/Test/**
2. In firebug or any other browser console execute loadDraft(testdata), copy the method call and sample data from here : **https://github.com/maina/Test/blob/gh-pages/build/js/sample_script.js**.
3. Change language to English and choose 'Yes' for the question 'Are there any married women between the ages of 13 - 49 live in this household?' to open a repeat section.
4. In the 'New woman registration' repeat select 'Yes' for the question 'Are you still menstruating?', 'Are you currently living with your husband?' question should show up.
5. Click on add (+) button to add a new repeat 
6. Note the new repeat opens up with 'Are you currently living with your husband?' question showing up and it should have been hidden

For a sample xform see: **https://github.com/maina/Test/tree/gh-pages/xform**

**Comment by MartijnR** [comment] 2016-07-13 15:45
Nice issue description! (except for the massive form).

The issue is that new repeats are not created in the model, when the form has been instantiated using loadDraft(testData). (check in console with `form.getModel().xml`)

Not sure if it's a bug yet. If this is urgent for you, try debugging FormModel.prototype.cloneRepeat (both in the virgin empty form, after creating repeats and after loadDraft()).

**Comment by maina** [comment] 2016-07-13 18:55
sorry for the large form. It's a bit urgent for us so I'll debug in the meantime as you've pointed out and see how it goes...thanks

**Comment by maina** [comment] 2016-07-19 11:10
I've debugged  FormModel.prototype.cloneRepeat method and seems like a new repeat is created in the model after this line executes $templateClone = $template.clone().insertAfter( $insertAfterNode ); but after loadDraft() it's not created. Not sure what could be wrong here...

**Comment by MartijnR** [comment] 2016-07-19 15:00
Thanks for that. I'll be happy to look at it once I have funding for it, or when it becomes urgent (i.e. pops up in Enketo Express). I'll mark it as a bug for now.

**Comment by MartijnR** [comment] 2016-07-25 22:45
This was a tricky one! It is caused by the fact that the instanceStr contains a repeat node with a `template` attribute. Enketo never submits or stores templates in a record, so it didn't expect this situation. Enketo is supposed to just ignore nodes with `template` and `jr:template` attributes in instanceStr. So the bug was that it didn't. That is now fixed. This means that in your sample instanceStr the whole `<woman template="">...</woman>` section will be completely discarded now (correct behavior).

So on your side, there may be some serious changes required, if that instanceStr, was an actual record   (not a hand-crafted record). If so:

1. Storing a user-entered value ("eisha") in a template would indicate a huge bug. I am not aware of that bug having been present in an old version of Enketo-core. I'm certain it's not there now. Maybe some non-enketo code was used to generate this XML record that has this bug?
2. It would be best if your record-storing mechanism obtains the record via form.getDataStr() if it doesn't already This means there should never be a template node in the stored/submitted record.

P.S. I wasn't actually able to reproduce the issue whereby the repeat was not cloned in the XML model, when using Enketo-Core and hardcoding your instanceStr in app.js. Maybe this is caused by you using an older version of enketo-core or otherwise the loadDraft code. In any case, I'm pretty sure we're talking about the same bug here. Could you check if it still occurs? If you want to test loading the same data, you should remove `template=\"\"` from instanceStr.

**Comment by MartijnR** [comment] 2016-07-26 16:46
@maina, @ukanga I am just making sure you see this

**Comment by ukanga** [comment] 2016-07-26 17:08
Thank you, will test this and get back to you.

**Comment by ukanga** [comment] 2016-07-26 19:17
@MartijnR you are right, I removed the `template=""` from the `instanceStr` and the repeat worked as expected. My fault was constructing the `instanceStr` from the form model instance which has the template attribute. 

Thanks again for looking into this.

**Comment by MartijnR** [comment] 2016-07-26 19:34
Great!

**Closed by MartijnR** 2016-07-26 19:34 UTC
Labels: bug
