### ISSUE TITLE
Bug: In web view, map zooms out as soon as clicked

### ISSUE THREAD

**Issue by answerquest** [enketo/enketo-core#314] opened 2015-09-18 09:57 UTC
Sample form : https://xhatj.enketo.org/webform (deployed from form on ona.io)

Typically, we have a habit of clicking and zooming out way to a location. When I click on the map, it might not be my final, selected position. Here, when if I have zoomed in to a location and click on a place, I'm doing it with the intention of moving that area to center view and then zooming in more to get a more accurate point.
But the map instantly zooms back out as soon as I click. I have to then zoom in all over again.

If I have searched for a place, then the zoomout happens to that zoom level, which is still bad. Still bothersome. Many users might never use the search and simply pan and zoom their way to the location. After clicking, users need to see where exactly they've clicked. So no point in making the map zoom all the way out on click. Please remove that line of code.

**Comment by MartijnR** [comment] 2015-09-18 14:45
Yes, I agree, I think. Seems duplicate of #259. Re-open if different.

**Closed by MartijnR** 2015-09-18 14:45 UTC

**Comment by answerquest** [comment] 2015-09-19 01:02
ok! Hadn't recognized it earlier as the text wasn't descriptive enough. I'll copy the problem description there in case it helps.

**Comment by MartijnR** [comment] 2015-09-20 22:29
thanks!
