### ISSUE TITLE
Provide method for obtaining Model without non-`relevant` fields

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#336] opened 2015-10-19 10:30 UTC
> #### 6.1.4 The relevant Property
> 
> Description: indicates whether the model item is currently _relevant_. Instance data nodes with this property evaluating to `false` are unavailable in the user interface and can be removed from submission serialization.
> — _http://www.w3.org/TR/xforms/#model-prop-relevant_

It would be very helpful to have a method similar to `Form.getDataStr()` which would allow fields with `relevant` evaluating `false` excluded.

Alternatively, `FormModel.getStr()` could be modified to always exclude these fields without breaking the spec.  However, this might have surprising effects if some users are relying on non-relevant data appearing in their form submission.

**Comment by MartijnR** [comment] 2015-10-19 17:30
You're right. This should actually be done. First we should find out if ODK Collect excludes those correctly (I think it does).

If it does, I'd be happy to get this added in a way that keeps the default behaviour the same (because it's definitely going to break stuff in various Enketo apps). Implementation will be messy as far as I can see. I think accessing form.getDataStr() with a non-default parameter that excludes relevants perhaps.

The reason I have never done this, is that the benefits of a smaller submission (or local storage size) didn't seem worth the effort for the current Enketo apps. It has become quite a bit more feasible to do this though with a recently-introduced better way of merging (partial) records into the model.

**Comment by MartijnR** [comment] 2016-12-21 22:01
confirmed that ODK Collect strips irrelevant fields from submission. They may actually simply remove all empty fields. [To check, because if so, then all servers would already support this]

That would be super-easy to implement too.

**Comment by MartijnR** [comment] 2017-02-03 23:50
depending on implementation this would also do b44dbd8bae1751f2741bb365d18fb558ff841976

**Comment by MartijnR** [comment] 2017-03-17 21:37
Don't strip relevant empty fields. It's helpful to know the distinction between empty vs. empty && irrelevant.

**Comment by dorey** [comment] 2017-03-18 01:29
Ping @eawag-rdm, who created eawag-rdm/kobo-post to focus on this issue.

I've started a discussion with and tested out how ODK Collect and Enketo preserve nodes of the XML submissions and I want to report that there might be another way to similarly flag fields that were skipped in Collect. Please see the results from submissions to this contrived example:

```
<!--
3 submissions from ODK Collect
--------------------------------
Minimized XML to demonstrate how collect strips nodes.
All comments are added by me. -@dorey
--> 

<!-- submission 1 . all questions have responses -->
<amJipsGQEQknybsUZp3qJw>
    <q1>Collect'd</q1>
    <q2_if_q1_has_response>C2</q2_if_q1_has_response>
    <group_zd4la81>
        <g1_q1>55</g1_q1>
    </group_zd4la81>
</amJipsGQEQknybsUZp3qJw>

<!-- submission 2 . partial response -->
<amJipsGQEQknybsUZp3qJw>
    <q1>Collect'd</q1>
    <q2_if_q1_has_response/> <!-- "q2_if_q1_has_response" was seen, but received no response -->
</amJipsGQEQknybsUZp3qJw>

<!-- submission 3 . no fields have responses -->
<amJipsGQEQknybsUZp3qJw>
    <q1/> <!-- q1 was seen but received no response -->
    <!-- q2_if_q1_has_response is not present -->
    <!-- third question in a group was not seen and is stripped out -->
</amJipsGQEQknybsUZp3qJw>
```

If @MartijnR wants to implement a similar stripping of unseen fields then I could ensure that Kobo + kobotoolbox/formpack parse the submissions and keep track of whether the response is a `null` response (e.g. `<q1/>`) or is removed from the instance because it is never seen.

Still uncertain: Is there a difference between `<q1/>` (with no chidl TextNode present) and `<q1></q1>` (with an empty TextNode).

**Comment by dorey** [comment] 2017-03-18 01:36
Pinging @hvwaldow  . (accidentally pinged your org in the previous comment)

**Comment by hvwaldow** [comment] 2017-03-20 11:36
Thanks for pinging, @dorey!

**Comment by MartijnR** [comment] 2017-03-20 15:02
thanks @dorey!

With "seen" do you mean "waas relevant at one point", "was relevant at time the record was marked 'final'" or something more complex about the page actually being swiped through by the user?

**Comment by MartijnR** [comment] 2017-03-21 17:44
after further discussion:

A new method exactly as @alxndrsn proposed is the way to go. 

In Enketo Express, we'll make this the default method to use to obtain the submission when a record is marked as final.

**Comment by dorey** [comment] 2017-03-21 22:01
Re: @MartijnR 's question about "seen" vs "relevant at finalization", I think relevant at finalization is good.

Though, it is tempting to try to find a way to squeeze some relevant information out of the experience that is not inherent in the survey. I think if we were to capture "seen" questions, it would provide an incomplete record of how the user progressed through the survey, and could be confusing. So relevant-at-finalization is good enough :+1:

**Closed** 2017-03-27 16:51 UTC
