### ISSUE TITLE
Enketo 6.2.0 changes display of multi-line text

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo-core#989] opened 2023-07-31 22:51 UTC
In Enketo 6.1.0, text questions with lots of text are displayed fully:
<img width="1131" alt="Screenshot 2023-07-31 at 15 42 09" src="https://github.com/enketo/enketo-core/assets/32369/751bf3bd-b0fd-4dfc-bdfb-e2238555db42">

In Enketo 6.2.0, they are not:
<img width="1080" alt="Screenshot 2023-07-31 at 15 46 05" src="https://github.com/enketo/enketo-core/assets/32369/54d54383-ec8e-47f8-9be2-81422cba6d23">

**Comment by lognaturel** [comment] 2023-08-02 21:32
I believe the issue is that with the grid theme, the expanding thing in the bottom right corner doesn't work. Does that sound right, @yanokwa?


[multiline-text.zip](https://github.com/enketo/enketo-core/files/12244979/multiline-text.zip)

I believe it was fixed by https://github.com/enketo/enketo-core/pull/990

**Comment by yanokwa** [comment] 2023-08-02 23:52
In 6.1.0, when you open the page, it shows everything (probably up to a limit) by default. 

I did not check if the expander works in 6.1.0. I think it did not work in 6.2.0, but I tried 6.2.0 a month ago, so my memory is not reliable.

**Comment by lognaturel** [comment] 2023-08-02 23:57
I can reproduce the expander not working. It sounds like additionally it’s expected that opening an existing instance expands as needed.

**Closed** 2023-08-03 18:47 UTC
Labels: bug
