### ISSUE TITLE
pulldata() in constraint won't work unless also present in a calculate field

### ISSUE THREAD

**Issue by Freeedim** [enketo/enketo-core#722] opened 2020-06-12 15:17 UTC
Hi there,

I use KoBoToolbox.

When I want to verify an input against the result of a pulldata('file01', 'a', 'b', ${c}), it won't work unless there is somewhere in the form a calculate field with pulldata('file01', 'x', 'y', ${z}). It's like if a given "media" file can only be fetched by a calculate field, to then be available to constraints.

You just need a single text field with a constraint using a pulldata() to be able to witness the problem. Add a second field that is a calculate with a pulldata() on the same file and the problem is solved.

The workaround is therefore pretty simple to implement, but it takes hours to find out that this is the problem. I think there should be a way to have pulldata() directly working for constraints.

Thanks for your attention

**Comment by MartijnR** [comment] 2020-06-12 15:29
Thank you! This sounds like a pyxform bug. I'll investigate and close this once I've file a bug report in pyxform.

It sounds like the issue is that pyxform doesn't automatically create an external instance reference if pulldata is (only) used in a constraint. So some of the wizardry we used to turn pulldata into a proper XPath function needs to be extended to usage in other columns.

**Comment by MartijnR** [comment] 2020-06-12 16:00
Hi @Freeedim, 

I am not yet able to reproduce this, so I am hoping you can help. It sounds like the XForm you are producing (when uploading your XLSForm to e.g. https://getodk.org/xlsform) does not include a reference such as `<instance id="fruits" src="jr://file-csv/file01.csv" />`

But when using [this form](https://docs.google.com/spreadsheets/d/1M7mW8oCuN8-8kgVj4jMQhpm4MXezT3v99XuyFkjKlmk/edit#gid=0) I do get such a reference. I think your usage may be subtly different.

It could also be an issue with the version of pyxform you are using of course, though I am not aware of this bug having occurred in the recent past.

**Comment by MartijnR** [comment] 2020-08-05 20:57
closed due to inability to reproduce

**Closed** 2020-08-05 20:56 UTC
