### ISSUE TITLE
Default for select-one not retained when parent question is changed

### ISSUE THREAD

**Issue by ajaydivakaran** [enketo/enketo-core#261] opened 2015-03-09 11:16 UTC
Questionnaire:

![screen shot 2015-03-09 at 4 44 24 pm](https://cloud.githubusercontent.com/assets/1208709/6553896/a1908df4-c67b-11e4-946b-c065c1588821.png)

Steps to reproduce:
1) Change 'showClinicOrPeople' from one option to another.
2) Go back to previous option.

Actual Result:
The default value is not retained.

Expected Result:
The default value should be retained.

**Comment by MartijnR** [comment] 2015-03-09 15:14
Thanks. Duplicate of #240

**Closed by MartijnR** 2015-03-09 15:14 UTC
